# Generated by Django 3.1.7 on 2021-04-13 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_commentcrm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentcrm',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
